<script setup lang="ts">
import { computed, reactive } from 'vue';

const haul = reactive({ payload: 90, cycle: 24, efficiency: 0.85, trucks: 4 });
const match = reactive({ excavatorBucket: 12, bucketCount: 5, fillFactor: 0.9, cycle: 30, truckCapacity: 90, truckCycle: 24 });
const availability = reactive({ scheduled: 12, operating: 9, standby: 1, delay: 1, breakdown: 1 });
const energy = reactive({ liter: 15000, kwh: 22000, ton: 12000 });
const angka = (value: unknown, digits = 2) => Number(value || 0).toLocaleString('id-ID', { maximumFractionDigits: digits });
const haulResult = computed(() => ({ hourly: haul.cycle > 0 ? (60 / haul.cycle) * haul.payload * haul.efficiency * haul.trucks : 0, daily: haul.cycle > 0 ? (60 / haul.cycle) * haul.payload * haul.efficiency * haul.trucks * 12 : 0 }));
const matchResult = computed(() => { const loader = match.bucketCount * match.excavatorBucket * match.fillFactor * (60 / match.cycle); const trucks = match.truckCapacity * (60 / match.truckCycle); return { loader, trucks, factor: trucks > 0 ? loader / trucks : 0, recommendation: loader > trucks * 1.1 ? 'Tambahkan truck atau kurangi waktu tunggu loading.' : trucks > loader * 1.1 ? 'Kurangi truck atau optimalkan cycle excavator.' : 'Match factor seimbang.' }; });
const availabilityResult = computed(() => { const scheduled = Math.max(1, availability.scheduled); return { pa: ((scheduled - availability.breakdown) / scheduled) * 100, ua: (availability.operating / scheduled) * 100, utilization: availability.scheduled > 0 ? (availability.operating / (availability.operating + availability.standby + availability.delay)) * 100 : 0 }; });
const energyResult = computed(() => { const gj = energy.liter * 0.0358 + energy.kwh * 0.0036; return { gj, intensity: energy.ton > 0 ? gj / energy.ton : 0, co2: energy.liter * 0.00268 + energy.kwh * 0.00087, cost: energy.liter * 14500 + energy.kwh * 1450 }; });
</script>

<template>
  <section class="grid gap-4 md:grid-cols-2"><article class="rounded-2xl bg-white border border-stone-100 shadow-card p-5"><h3 class="font-bold">Produktivitas Hauling</h3><p class="text-[11px] text-stone-500 mt-1">Estimasi ton/jam dari payload, cycle time, efisiensi, dan jumlah truck.</p><div class="grid grid-cols-2 gap-2 mt-4"><input v-model.number="haul.payload" type="number" placeholder="Payload ton" class="rounded-lg border-stone-200 text-[12px]"><input v-model.number="haul.cycle" type="number" placeholder="Cycle menit" class="rounded-lg border-stone-200 text-[12px]"><input v-model.number="haul.efficiency" type="number" step=".01" placeholder="Efisiensi 0-1" class="rounded-lg border-stone-200 text-[12px]"><input v-model.number="haul.trucks" type="number" placeholder="Jumlah truck" class="rounded-lg border-stone-200 text-[12px]"></div><div class="grid grid-cols-2 gap-2 mt-4"><div class="rounded-xl bg-stone-50 p-3"><small class="text-stone-400">Ton/jam</small><b class="block text-lg">{{ angka(haulResult.hourly) }}</b></div><div class="rounded-xl bg-stone-50 p-3"><small class="text-stone-400">Ton/shift 12 jam</small><b class="block text-lg">{{ angka(haulResult.daily) }}</b></div></div></article>
    <article class="rounded-2xl bg-white border border-stone-100 shadow-card p-5"><h3 class="font-bold">Truck–Excavator Match Factor</h3><p class="text-[11px] text-stone-500 mt-1">Menentukan keseimbangan kapasitas loading dan hauling.</p><div class="grid grid-cols-2 gap-2 mt-4"><input v-model.number="match.excavatorBucket" type="number" step=".1" placeholder="Bucket m³" class="rounded-lg border-stone-200 text-[12px]"><input v-model.number="match.bucketCount" type="number" placeholder="Bucket/truck" class="rounded-lg border-stone-200 text-[12px]"><input v-model.number="match.fillFactor" type="number" step=".01" placeholder="Fill factor" class="rounded-lg border-stone-200 text-[12px]"><input v-model.number="match.cycle" type="number" placeholder="Cycle excavator" class="rounded-lg border-stone-200 text-[12px]"><input v-model.number="match.truckCapacity" type="number" placeholder="Kapasitas truck" class="rounded-lg border-stone-200 text-[12px]"><input v-model.number="match.truckCycle" type="number" placeholder="Cycle truck" class="rounded-lg border-stone-200 text-[12px]"></div><div class="mt-4 rounded-xl bg-stone-50 p-3"><div class="flex justify-between text-[12px]"><span>Match factor</span><b>{{ angka(matchResult.factor, 2) }}</b></div><p class="text-[11px] text-cam-orange mt-2">{{ matchResult.recommendation }}</p></div></article>
    <article class="rounded-2xl bg-white border border-stone-100 shadow-card p-5"><h3 class="font-bold">Availability & Utilization</h3><p class="text-[11px] text-stone-500 mt-1">Pisahkan waktu rusak, standby, delay, dan waktu benar-benar menghasilkan.</p><div class="grid grid-cols-2 gap-2 mt-4"><input v-model.number="availability.scheduled" type="number" placeholder="Jam terjadwal" class="rounded-lg border-stone-200 text-[12px]"><input v-model.number="availability.operating" type="number" placeholder="Jam operating" class="rounded-lg border-stone-200 text-[12px]"><input v-model.number="availability.standby" type="number" placeholder="Standby" class="rounded-lg border-stone-200 text-[12px]"><input v-model.number="availability.delay" type="number" placeholder="Delay" class="rounded-lg border-stone-200 text-[12px]"><input v-model.number="availability.breakdown" type="number" placeholder="Breakdown" class="rounded-lg border-stone-200 text-[12px]"></div><div class="grid grid-cols-3 gap-2 mt-4 text-center"><div class="rounded-xl bg-stone-50 p-3"><small class="text-[10px] text-stone-400">PA</small><b class="block">{{ angka(availabilityResult.pa, 1) }}%</b></div><div class="rounded-xl bg-stone-50 p-3"><small class="text-[10px] text-stone-400">UA</small><b class="block">{{ angka(availabilityResult.ua, 1) }}%</b></div><div class="rounded-xl bg-stone-50 p-3"><small class="text-[10px] text-stone-400">Utilisasi</small><b class="block">{{ angka(availabilityResult.utilization, 1) }}%</b></div></div></article>
    <article class="rounded-2xl bg-white border border-stone-100 shadow-card p-5"><h3 class="font-bold">Energy Intensity & Carbon</h3><p class="text-[11px] text-stone-500 mt-1">Simulasi dampak input fuel dan listrik terhadap produksi.</p><div class="grid grid-cols-2 gap-2 mt-4"><input v-model.number="energy.liter" type="number" placeholder="Solar liter" class="rounded-lg border-stone-200 text-[12px]"><input v-model.number="energy.kwh" type="number" placeholder="Listrik kWh" class="rounded-lg border-stone-200 text-[12px]"><input v-model.number="energy.ton" type="number" placeholder="Produksi ton" class="rounded-lg border-stone-200 text-[12px] col-span-2"></div><div class="grid grid-cols-2 gap-2 mt-4"><div class="rounded-xl bg-stone-50 p-3"><small class="text-stone-400">Intensitas</small><b class="block">{{ angka(energyResult.intensity, 4) }} GJ/ton</b></div><div class="rounded-xl bg-stone-50 p-3"><small class="text-stone-400">Emisi</small><b class="block">{{ angka(energyResult.co2, 2) }} tCO₂e</b></div><div class="rounded-xl bg-stone-50 p-3 col-span-2"><small class="text-stone-400">Estimasi biaya energi</small><b class="block">Rp {{ angka(energyResult.cost, 0) }}</b></div></div></article>
  </section>
</template>
